services:
  postgres:
    image: postgres:latest
    container_name: student_manager_app_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: students_db
    ports:
      - "5432:5432"